version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip3 install poetry
      - poetry install
  build:
    commands:
      - poetry run pytest --junitxml=junitxml.xml

reports:
  pytest_reports:
    files:
      - junitxml.xml
    file-format: JUNITXML

cache:
  paths:
    - ~/.cache/pip
    - ~/.cache/pypoetry
